#use conda env create --file environment.yml to creat the environment and use
#the render.py to show results
name: environment
dependencies:
  - python
  - pip
  - pip:
    - tensorflow
    - matplotlib
    - numpy
    - gym
    - box2d
